title: Numbers of Life
author:
    name: Stephen Thomas
    url: http://sathomas.me
description: "Musings at the intersection of mathematics and biology"
tagline: "Musings at the intersection of mathematics and biology"
production_url : http://numbersof.life
permalink: /:year/:month/:day/:title”
